"""ID 生成：跨存储/预分配/对外业务标识用 UUIDv7（时间有序、字符串可比较）。

DB 内部主键统一走 BIGINT GENERATED BY DEFAULT AS IDENTITY（自增），见 00 文档 §5.5。
"""

from uuid_utils import uuid7


def new_uuid7() -> str:
    """生成 UUIDv7 字符串。"""
    return str(uuid7())
